### ISSUE TITLE
Question about a section of the Documentation

### ISSUE THREAD

**Issue by Hunanbean** [studiostry/UE4MBLabCharacterStudy#11]
Hello.
The documentation states:

>      
    15) Create an instance of Face and Voice manager in a map by dragging the actor in
    16) Select that actor and look at the details panel
    17) Under import animation
        a. paste clipboard contents in Face Data Stream
        b. Click Prepare Input From Voice Tools Button
        c. notice the Output Face Time Data gets populated 
        d. right click the array and click copy

Although I can select the Face and Voice manager, i do not see the Import Animation, or Face Data Stream, or Voice Tools Button, so i have no way to follow this section. Has the process changed, or am i just truly missing something at this point?

Thank you

**Comment by fblah** [comment]
Hi sorry about the documentation being out of date. I'll have to delete this.

Follow this video instead:
[https://www.youtube.com/watch?v=WLRngOwCVB0](https://www.youtube.com/watch?v=WLRngOwCVB0)

**Comment by Hunanbean** [comment]
Thank you, I am finding all of your videos on the subject to be very helpful. Continuing research now
