### ISSUE TITLE
Unable to get data in to Sequencer

### ISSUE THREAD

**Issue by Hunanbean** [studiostry/UE4MBLabCharacterStudy#12]
Hello.
Ok, so everything is working quite well! I was able to readily adapt your system for use with my custom character and phonemes, thanks to your videos and the way you wrote the system. Very logical and understandable. I have run into one issue though, that i cannot seem to work around.

When trying to 'Edit in Sequencer' i get the message "Need a valid Sequence opened". I do have a level sequence open, but it does not recognize that as valid. I have little to no experience with sequencer and i assume i am just missing something basic. I have watched all of your videos more than once, but in your video on the subject, it just works. Any insight is much appreciated.

Thank you

p.s. Now that i have gotten into your project, all i can say is Wow. What you have made is truly awesome!

**Comment by fblah** [comment]
Hi again!

Thank you for your comment.
I identified the issue, the latest update fixes it.

fBlah

**Comment by Hunanbean** [comment]
Thank you very much!
It now works just as expected.
