### ISSUE TITLE
Request: As a plugin

### ISSUE THREAD

**Issue by Hunanbean** [studiostry/UE4MBLabCharacterStudy#13]
Hello again. After having tried and failed, at least 5 times, i am writing to ask if you have any plans to make this into a plugin that can be moved between projects.

Thank you again for the project. I fully understand that making this into a plugin may not be in your plans. if not, c'est la vie.

Be well!

**Comment by Hunanbean** [comment]
I may have figured out my error. I neglected to clean up redirectors in one of the folder. I will continue and see if i can accomplish this task.

**Comment by fblah** [comment]
The project is intended to be more of study/guide for workflow, also all the code and assets can be easily migrated to your own project.

Even the c++ code is nothing too fancy and can be easily ported.

You can ping us on discord if you encounter any roadblocks.

**Comment by Hunanbean** [comment]
Understood.
AH! I missed the fact you had a discord. Thank you
