### ISSUE TITLE
Errors during init the projet in UE4

### ISSUE THREAD

**Issue by Br4x** [studiostry/UE4MBLabCharacterStudy#3]
Hi I get these errors when launching the project in Unreal
![errors](https://user-images.githubusercontent.com/4102402/82416826-fbd5c580-9a7a-11ea-89bd-acfd6c683dab.PNG)

**Comment by fblah** [comment]
The project requires an external plugin for animation mirrorring. When cloning make sure you use the command recursive to download additional dependencies and sub modules.

Check this link to learn how to clone recursively with sub modules:
https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

The plugin is available here:
https://github.com/fblah/AnimNode/tree/a1518b7272b05a999b273e538cbdfe240a43f6f8

The plugin must be placed inside this folder:
https://github.com/studiostry/UE4MBLabCharacterStudy/tree/master/Plugins
