### ISSUE TITLE
Is it possible to export MB Lab morph target (body and face)

### ISSUE THREAD

**Issue by Br4x** [studiostry/UE4MBLabCharacterStudy#4]
Hi, me again :p
I intend to do a character creation in my game, and i was wondering if it was possible to export morph target like age and mass tone to UE4.

**Comment by fblah** [comment]
You will need to modify the manuel bastioni plugin to in blender to export those morphs as well. I am not sure about how to do that at this moment. 

Alternatively you can manually make those morphs and export it with your character.

**Comment by Br4x** [comment]
Thanks a lot, I will check that :D

**Comment by fblah** [comment]
Please close the issue if satisfied. Further questions might be out of the scope of this project but you can use the discord server for that discussion.
