### ISSUE TITLE
Request for update to 4.25

### ISSUE THREAD

**Issue by Hunanbean** [studiostry/UE4MBLabCharacterStudy#5]
Thank you for demonstrating all of this. It is truly useful. I have however moved on to 4.25 and will be heading quickly to 4.26 for multiple reasons.

I am writing simply to request an update to 4.25 so i can continue trying to learn what you have put together.
(also, due to limited space, having both versions installed is difficult)

Thanks again, and be well!

**Comment by fblah** [comment]
I pushed the updated version

**Comment by Hunanbean** [comment]
Thank you very much!
