### ISSUE TITLE
Requesting update to 4.26 please

### ISSUE THREAD

**Issue by Hunanbean** [studiostry/UE4MBLabCharacterStudy#6]
Hello again. I am just openeing an issue to request an update to 4.26, which is the only version i have installed and therfore cannot attempt to rebuild from source using the usual tricks.
Thank you
Also a reminder that MakeHuman is now CC0 and that there is the full 39 viseme set of shapekeys for use with it and Papagayo-NG

**Comment by fblah** [comment]
Hi, I have updated the binaries to 4.26. Please review and close the issue :)

**Comment by Hunanbean** [comment]
Thank you very much! :)
