### ISSUE TITLE
Morph Target in 4.26

### ISSUE THREAD

**Issue by xl0g** [studiostry/UE4MBLabCharacterStudy#7]
Hey, 

i just tried to use morph targets, but as you said in a previous issue, it could be done by modifying the plugin, is it now available without modifying ? Thanks

**Comment by fblah** [comment]
The plugin now has the nodes available in blueprints so you can access them using the blueprinting system.

**Comment by xl0g** [comment]
I found a way using Key shapes in blender and import it on UE thanks ! I starred this
