### ISSUE TITLE
In UE workflow 

### ISSUE THREAD

**Issue by fromEON** [studiostry/UE4MBLabCharacterStudy#8]
Can't I generate characters inside UE

**Comment by fblah** [comment]
No, MBLab is licensed for use with Blender. (Its license prevents users from using the character database outside of original package made for Blender - Exported Characters can be used in external applications like UE4 as long Attribution is given to Manuel Bastioni). Read the license for more details.

**Comment by fromEON** [comment]
Anyhow you make work life easier by tweaking import from b3d to UE 👍
