### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by Hunanbean** [studiostry/UE4MBLabCharacterStudy#9]
Hello again. I am Finally able to dive into this project, but i get the following error:

`This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response`

This ofcourse means what gets downloaded is incomplete and therefore not functioning
Is there perhaps an alternate download location, such as google drive?

Thank you, and best wishes

**Comment by fblah** [comment]
I can't afford to purchase more LFS. You can get around this by downloading the repository from the browser and it will exclude large files that are stored on LFS, which is the .blend project reference. If you want an alternative link was already provided in the project readme.

**Comment by Hunanbean** [comment]
I understand. I cannot afford it either. I consider it somewhat absurd that
a large corporation (microsoft, who owns github) is even attempting to
charge for it, considering the benefit they get from all the open code
contributions. But I digress.
I did not realize the only file contained in the LFS portion was the
.blend, due to the fact that the example .dat file was not present in the
tools directory. This led me to believe more files were missing, beyond the
expected LFS content. Since you have clarified, I will get back to work! I
am going to attempt to adapt your system to the extended 39 viseme system i
made for MakeHuman. Once successful, I will be back in touch. Thank you
again for your always quick responses, and a sincere thank you for your
work as a whole. Be well!
